=== inf23tig04/inf23tig04/TrabalhoGrupo_TI/Codigo/xml/atletismo.xsd
<?xml version = "1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="corrida_de_pista">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="tipos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="sprint">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="distancias">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name = "distancia" type = "xs:string"/>
                                                <xs:element name = "distancia" type = "xs:string"/>
                                                <xs:element name = "distancia" type = "xs:string"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="recordes">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="recorde">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="prova" type="xs:string"/>
                                                            <xs:element name="tempo" type="xs:string"/>
                                                            <xs:element name="atleta" type="xs:string"/>
                                                            <xs:element name="pais" type="xs:string"/>
                                                            <xs:element name="data" type="xs:string"/>
                                                            <xs:element name="local" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="recorde">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="prova" type="xs:string"/>
                                                            <xs:element name="tempo" type="xs:string"/>
                                                            <xs:element name="atleta" type="xs:string"/>
                                                            <xs:element name="pais" type="xs:string"/>
                                                            <xs:element name="data" type="xs:string"/>
                                                            <xs:element name="local" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="recorde">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="prova" type="xs:string"/>
                                                            <xs:element name="tempo" type="xs:string"/>
                                                            <xs:element name="atleta" type="xs:string"/>
                                                            <xs:element name="pais" type="xs:string"/>
                                                            <xs:element name="data" type="xs:string"/>
                                                            <xs:element name="local" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="meio_fundo">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="distancias">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name = "distancia" type = "xs:string"/>
                                                <xs:element name = "distancia" type = "xs:string"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="recordes">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="recorde">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="prova" type="xs:string"/>
                                                            <xs:element name="tempo" type="xs:string"/>
                                                            <xs:element name="atleta" type="xs:string"/>
                                                            <xs:element name="pais" type="xs:string"/>
                                                            <xs:element name="data" type="xs:string"/>
                                                            <xs:element name="local" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="recorde">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="prova" type="xs:string"/>
                                                            <xs:element name="tempo" type="xs:string"/>
                                                            <xs:element name="atleta" type="xs:string"/>
                                                            <xs:element name="pais" type="xs:string"/>
                                                            <xs:element name="data" type="xs:string"/>
                                                            <xs:element name="local" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="obstaculos">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="distancia" type = "xs:string"/>
                                    <xs:element name="recordes">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="recorde">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="prova" type="xs:string"/>
                                                            <xs:element name="tempo" type="xs:string"/>
                                                            <xs:element name="atleta" type="xs:string"/>
                                                            <xs:element name="pais" type="xs:string"/>
                                                            <xs:element name="data" type="xs:string"/>
                                                            <xs:element name="local" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="fundo">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="distancias">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name = "distancia" type = "xs:string"/>
                                                <xs:element name = "distancia" type = "xs:string"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="recordes">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="recorde">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="prova" type="xs:string"/>
                                                            <xs:element name="tempo" type="xs:string"/>
                                                            <xs:element name="atleta" type="xs:string"/>
                                                            <xs:element name="pais" type="xs:string"/>
                                                            <xs:element name="data" type="xs:string"/>
                                                            <xs:element name="local" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                                <xs:element name="recorde">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="prova" type="xs:string"/>
                                                            <xs:element name="tempo" type="xs:string"/>
                                                            <xs:element name="atleta" type="xs:string"/>
                                                            <xs:element name="pais" type="xs:string"/>
                                                            <xs:element name="data" type="xs:string"/>
                                                            <xs:element name="local" type="xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== inf23tig04/inf23tig04/TrabalhoGrupo_TI/Codigo/xml/atletismo.xml
<?xml version = "1.0" encoding = "utf-8" ?>

<corrida_de_pista xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="atletismo.xsd">
    <tipos>
        <sprint>
            <distancias>
                <distancia>100 m</distancia>
                <distancia>200 m</distancia>
                <distancia>400 m</distancia>
            </distancias>
            <recordes>
                <recorde>
                    <prova>100 m</prova>
                    <tempo>9s58</tempo>
                    <atleta>Usain Bolt</atleta>
                    <pais>Jamaica</pais>
                    <data>16/08/2009</data>
                    <local>Berlim</local>
                </recorde>
                <recorde>
                    <prova>200 m</prova>
                    <tempo>19s19</tempo>
                    <atleta>Usain Bolt</atleta>
                    <pais>Jamaica</pais>
                    <data>20/08/2009</data>
                    <local>Berlim</local>
                </recorde>
                <recorde>
                    <prova>400 m</prova>
                    <tempo>43s03</tempo>
                    <atleta>Wayde van Niekerk</atleta>
                    <pais>África do sul</pais>
                    <data>14/08/2016</data>
                    <local>Rio de Janeiro</local>
                    </recorde>
            </recordes>
        </sprint>
        <meio_fundo>
            <distancias>
                <distancia>800 m</distancia>
                <distancia>1500 m</distancia>
            </distancias>
            <recordes>
                <recorde>
                    <prova>800 m</prova>
                    <tempo>1min40s91</tempo>
                    <atleta>David Rudisha</atleta>
                    <pais>Quénia</pais>
                    <data>09/08/2012</data>
                    <local>Londres</local>
                </recorde>
                <recorde>
                    <prova>1500 m</prova>
                    <tempo>3min26s00</tempo>
                    <atleta>Hicham El Guerrouj</atleta>
                    <pais>Marrocos</pais>
                    <data>14/07/1998</data>
                    <local>Roma</local>
                </recorde>
            </recordes>
        </meio_fundo>
        <obstaculos>
            <distancia>3000 m</distancia>
            <recordes>
                <recorde>
                    <prova>3000 m</prova>
                    <tempo>7min53s63</tempo>
                    <atleta>Saif Saaeed</atleta>
                    <pais>Qatar</pais>
                    <data>03/11/2004</data>
                    <local>Bruxelas</local>
                </recorde>
            </recordes>
        </obstaculos>
        <fundo>
            <distancias>
                <distancia>5000 m</distancia>
                <distancia>10000 m</distancia>
            </distancias>
            <recordes>
                <recorde>
                    <prova>5000 m</prova>
                    <tempo>12min35s36</tempo>
                    <atleta>Joshua Cheptegei</atleta>
                    <pais>Uganda</pais>
                    <data>14/08/2020</data>
                    <local>Mônaco</local>
                </recorde>
                <recorde>
                    <prova>10000 m</prova>
                    <tempo>26min11s00</tempo>
                    <atleta>Joshua Cheptegei</atleta>
                    <pais>Uganda</pais>
                    <data>07/09/2020</data>
                    <local>Valência</local>
                </recorde>
            </recordes>
        </fundo>
    </tipos>
</corrida_de_pista>
